### ISSUE TITLE
Docs don't mention that pgcrypto extension is required

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-authentication-service#1557] opened 2023-08-21 10:58 UTC
```
$ docker run --network=host -v $(pwd)/tests-e2e/mas-config.yaml:/config.yaml ghcr.io/matrix-org/matrix-authentication-service:main database migrate

Error: could not run migrations

Caused by:
    0: while executing migrations: error returned from database: extension "pgcrypto" is not available
    1: error returned from database: extension "pgcrypto" is not available
    2: extension "pgcrypto" is not available
```

Looking at https://matrix-org.github.io/matrix-authentication-service/setup/database.html

**Comment by sandhose** [comment] 2023-08-23 10:19
This is weird, because the migration should do the `CREATE EXTENSION` for you. I can't find the PR/issue about that, but it was already discussed before.
Part of the issue is that `pgcrypto` was only marked as `trusted` starting Postgres 13, which means that before that version, you had to be a superuser to enable it. What version of Postgres are you running?

I'm also tempted to just get rid of the `pgcrypto` dependency, because it's only really used to generate random job IDs in the job queue, and that could just be done on the Rust side instead.

**Comment by DMRobertson** [comment] 2023-08-23 10:22
Postgres 15.1, on Fedora (this is me testing locally). Its distribution of postgres didn't have pgcrypto available by default; I had to `dnf install postgresql-contrib`. Maybe if I'd run `database migrate after that` it would have worked just fine.

**Closed** 2023-08-23 16:46 UTC
